name: github-tag-release
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  github-tag-create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          
  github-tag-release:
    needs: github-tag-create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^release: v(.*)$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}