name: Combine action-autotag with additional-tags-action

on:
  push:
    branches:
      - develop

jobs:
  tag-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: valitydev/action-autotag@v1

      - uses: vweevers/additional-tags-action@v1
